In [1]:
class Perceptron():
    """Object representing perceptron with two inputs.

    Attributes:
        e: A training set.
        w0: Bias weight.
        w1: The weight of the first input.
        w2: The weight of the second input.
        epochs: Number of epochs before stabilisation.
    """
    def __init__(self, e, activation_function = lambda s: 1 if s > 0 else -1):
        '''Initialises Perceptron object.'''
        self.w0 = 0
        self.w1 = 0
        self.w2 = 0
        self.e = e
        self.activation_function = activation_function

    def train(self):
        """Trains perceptron."""
        self.epochs = 1
        stable = False
        while not stable:
            stable = True
            for example in self.e:
                print(example)
                if self.classify(example[1], example[2]) == example[3]:
                    pass
                else:
                    self.w0 += example[3] * example[0]
                    self.w1 += example[3] * example[1]
                    self.w2 += example[3] * example[2]
                    stable = False
            if not stable:
                self.epochs += 1

    def classify(self, x1, x2):
        """Classifies an object."""
        s = (self.w1 * x1) + (self.w2 * x2) + self.w0
        return self.activation_function(s)



In [2]:
from typing import Callable

import numpy as np



"""Contains NeuralNetwork class definition.

Run after running the Data Preprocessing notebook.
"""

class NeuralNetwork:
    """A neural network with single hidden layer.
    
    Attributes:
        n_hidden_nodes: Number of hidden nodes.
        training_set: Set that instance is to be trained on.
        test_set: Set that instance is to be tested on.
        activation_functions: Activation function used for the neural network.
        step_size: Step size parameter.
        weights: Weights for hidden layer.
        biases: Biases for hidden layer.
        layers: List of network's layers (excluding input layer).
    
    """
    
    def __init__(
        self,
        n_hidden_nodes: int,
        training_set: np.ndarray,
        test_set: np.ndarray,
        activation_functions: [Callable],
        step_size: float = 0.1
    ):
        """Initialises a NeuralNetwork instance.
        """
        # TODO: Assign param values to the attributes.
        # TODO: Assign **random** small weights and biases to all cells.
        # TODO: Choose a small step size parameter (0.1).
        
        # Input is a matrix where each row is one instance
        self.n_hidden_nodes = n_hidden_nodes
        self.training_set = training_set
        self.test_set = test_set
        self.step_size = step_size
        pass
    
    def train(self):
        """Trains NeuralNetwork instance.
        """
        # TODO: 
        while True:
            for item in self.training_set:
                # Make forward pass through the network. Compute
                # - weighted sums
                # - S_j
                # - activations u_j = f(s_j) for every node
                # badkward pass though the network.
                # Update the weights.
                # output = np.dot(weights, inputs) + biases
                pass
        
    def test(self):
        """Tests NeuralNetwork instance.
        """
        pass
    
    def run(self):
        """Runs NeuralNetwork.
        """
        pass
    
    

## Batch Learning

Batch size may improve efficiency. Showing all sampes at once can cause overfitting. It will be bad at generalsing.

Typical batch size: 32



In [3]:
inputs = [[1, 2, 3, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2, 0.8, -0.5, 1.0],
          [0.5, -.91, 0.26, -0.5],
          [-0.26, -.27, 0.17, 0.87]]

biases = [2, 3, 0.5]


weights2 = [[0.1, -0.14, 0.5],
          [-0.5, 0.12, -0.33],
          [-0.44, 0.73, -0.13]]

biases2 = [-1, 2, -0.5]

layer1_outputs = np.dot(inputs, np.array(weights).T) + biases

layer2_outputs = np.dot(layer1_outputs, np.array(weights2).T) + biases2

print(layer2_outputs)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


## Feature Data Set

Feature data set is usaully denoted with `X`.

Labels are usually denoted with `y`.

In [4]:
def sigmoid(x):
    """Calculates output of the Sigmoid function for given `x`.
    """
    return 1 / (1 + np.e ** (-x))

print(sigmoid(3))


# Vectorise Sigmoid Function.
sigmoid_vectorised = np.vectorize(sigmoid)

0.9525741268224331


In [5]:
np.random.seed(0)

X = [[1, 2, 3, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]

class Layer:
    """Hidden Layer of a neural network.
    
    Attributes:
        weights: set of weights of the layer.
        biases: set of biases of the layer.
        activation_function: Activation Function of the layer.
        number_of_inputs: Number of inputs in the layer.
        output: the most recent output of the layer.
    """
    def __init__(self,
                 number_of_inputs: int,
                 number_of_neurons: int,
                 activation_function: Callable
                ):
        """Initialises a NeuralNetwork instance.
        """
        self.activation_function = activation_function
        random_generator = np.random.default_rng(5)
        #NNFS self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        low = -2 / number_of_neurons
        high = 2 / number_of_neurons
        self.weights = random_generator.uniform(
            low=low,
            high=high,
            size=(number_of_inputs, number_of_neurons)
        )
        self.biases = random_generator.uniform(
            low=low,
            high=high,
            size=(1, number_of_neurons)
        )
    
    def forward_pass(self, inputs: np.ndarray):
        """Does the forward pass through the layer.
        
        Arguments:
            inputs: Inputs to the layer.
        """
        self.sum = np.dot(inputs, self.weights) + self.biases
        self.output = self.activation_function(self.sum)
        
    def backward_pass(self):
        """Does the backward pass through the layer.
        """
        
layer1 = Layer(4, 5, sigmoid_vectorised)
layer2 = Layer(5, 2, sigmoid_vectorised)

layer1.forward_pass(X)
#print(layer1.output)
layer2.forward_pass(layer1.output)
print(layer2.output)

[[0.44013248 0.47013056]
 [0.49378334 0.53258975]
 [0.33949971 0.51147958]]


## Activation Functions

Every node on hidden layers and output layer have an activation function.

ReLU

sigmoid func has gradient problem.

## Learning Rate

Gradient of the error function

Too small weights - stuck in local minima